# Generated by Django 2.1.4 on 2019-01-22 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('website', models.CharField(max_length=100, verbose_name='website')),
                ('contact_number', models.CharField(max_length=50, verbose_name='contact number')),
                ('time_zone', models.CharField(max_length=100, verbose_name='time zone')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=100, verbose_name='location name')),
                ('contact_number', models.CharField(max_length=50, verbose_name='contact number')),
                ('contact_email', models.CharField(max_length=50, verbose_name='contact email')),
                ('address', models.TextField(verbose_name='physical address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('zip_code', models.CharField(max_length=50, null=True, verbose_name='zip code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
