# Generated by Django 2.1.4 on 2019-01-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.CharField(max_length=50, null=True, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='time_zone',
            field=models.CharField(max_length=100, null=True, verbose_name='time zone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=100, null=True, verbose_name='website'),
        ),
    ]
