# Generated by Django 2.1.4 on 2019-02-09 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20190208_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('appointment_color', models.CharField(max_length=50, verbose_name='appointment color')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('description', models.TextField(verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_groups', to='core.Company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('description', models.TextField(verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.Company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.ServiceGroups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
