# Generated by Django 2.1.4 on 2019-02-09 22:25

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190209_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=None, default_currency='USD', max_digits=10, null=True, verbose_name='discount price'),
        ),
    ]
