# Generated by Django 2.1.4 on 2019-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190209_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='duration',
            field=models.IntegerField(default=15, verbose_name='duration (in mins)'),
        ),
    ]
