# Generated by Django 2.1.4 on 2019-02-19 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20190215_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
