# Generated by Django 2.1.4 on 2019-02-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190220_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategories',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='products',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='servicegroups',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='services',
            name='creator',
        ),
    ]
