# Generated by Django 2.1.4 on 2019-02-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190220_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.Products')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.ProductVariants')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
