# Generated by Django 2.1.4 on 2019-02-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productstockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesClosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('closed_date', models.DateField(verbose_name='date closed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='time_slot_interval',
            field=models.IntegerField(default=15, verbose_name='time slot interval'),
        ),
        migrations.AddField(
            model_name='datesclosed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_closed', to='core.Company'),
        ),
    ]
