# Generated by Django 2.1.4 on 2019-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190222_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='datesclosed',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='locations',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='products',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='productstockhistory',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='servicegroups',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='services',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
