# Generated by Django 2.1.4 on 2019-02-24 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190223_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('delete_status', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('subject', models.CharField(max_length=100, verbose_name='email subject')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_before', models.BooleanField(default=True, verbose_name='sent before appointment')),
                ('minutes', models.IntegerField(default=15, verbose_name='minutes before/after appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='daily closing time'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='daily opening time'),
        ),
        migrations.AddField(
            model_name='datesclosed',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='locations',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productstockhistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='servicegroups',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cancellation_limit',
            field=models.IntegerField(default=3, verbose_name='max hours to cancellation'),
        ),
        migrations.AddField(
            model_name='autonotifications',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_notifications', to='core.Company'),
        ),
    ]
