# Generated by Django 2.1.4 on 2019-03-01 14:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190301_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='BookingPets',
        ),
        migrations.DeleteModel(
            name='BookingProducts',
        ),
        migrations.DeleteModel(
            name='BookingServices',
        ),
    ]
