# Generated by Django 2.1.4 on 2019-03-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190301_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='day')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='core.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='datesclosed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datesclosed',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='datesclosed',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='datesclosed',
            name='updated_at',
        ),
    ]
