# Generated by Django 2.1.4 on 2019-03-09 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190304_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpets',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='orderpets',
            name='pet',
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.CustomerPets'),
        ),
        migrations.DeleteModel(
            name='OrderPets',
        ),
    ]
