# Generated by Django 2.1.4 on 2019-03-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190309_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_duration',
            field=models.IntegerField(null=True, verbose_name='total duration'),
        ),
    ]
