# Generated by Django 2.1.4 on 2019-03-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190309_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='booking',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderservices',
            old_name='booking',
            new_name='order',
        ),
    ]
