# Generated by Django 2.1.4 on 2019-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190309_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='products/images/default-pro.jpg', upload_to='products/images/'),
        ),
    ]
