# Generated by Django 2.1.4 on 2019-03-11 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_products_image'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Messages',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='active')),
        #         ('delete_status', models.BooleanField(default=False, verbose_name='deleted')),
        #         ('subject', models.CharField(max_length=200, verbose_name='subject')),
        #         ('message', models.TextField(verbose_name='message')),
        #         ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
        #         ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='unit_price_currency',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='orderservices',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='products',
            name='retail_price_currency',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='retail_price_currency',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='products/images/default-pro.jpg', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='retail price'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='retail price'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
