# Generated by Django 2.1.4 on 2019-03-12 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_auto_20190312_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='retail price'),
        ),
    ]
