# Generated by Django 2.1.4 on 2019-03-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190318_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='retail_price',
        ),
    ]
