# Generated by Django 2.1.4 on 2019-04-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('delete_status', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('subject', models.CharField(max_length=100, verbose_name='email subject')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_before', models.BooleanField(default=True, verbose_name='sent before appointment')),
                ('minutes', models.IntegerField(default=15, verbose_name='minutes before/after appointment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_notifications', to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
