# Generated by Django 2.1.4 on 2019-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20190123_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
