# Generated by Django 2.1.4 on 2019-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20190305_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_key_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
