# Generated by Django 2.1.4 on 2019-04-14 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daysoff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='datesclosed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_closed', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='groomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
