# Generated by Django 2.1.4 on 2019-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190414_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='groomer',
        ),
    ]
