# Generated by Django 2.1.4 on 2019-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_bankaccountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=20, null=True, verbose_name='code'),
        ),
    ]
