# Generated by Django 2.1.4 on 2019-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190414_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='booking_type',
            field=models.CharField(default='in-house', max_length=50, verbose_name='booking type'),
        ),
    ]
